#pragma once

#ifndef DAK_QUASITILER_TILING_POINT_H
#define DAK_QUASITILER_TILING_POINT_H

#include <dak/geometry/point.h>


namespace dak::quasitiler
{
   ////////////////////////////////////////////////////////////////////////////
   //
   // A 2-dimension tiling point.
   //
   // Generated by the projection of a n-diemnsional grid.

   using tiling_point_t = geometry::point_t;
}

#endif /* DAK_QUASITILER_TILING_POINT_H */
